version: "3.9"
services:
  nginx:
    container_name: laravel_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../
        target: /var/www/html
      - type: bind
        source: ./docker/nginx/conf/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./docker/nginx/conf/default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
      - 30443:443
    networks:
      app-net:
        ipv4_address: 172.16.238.10
    depends_on:
      - php

  php:
    container_name: laravel_php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: php-fpm:8.2.13-fpm
    volumes:
      - type: bind
        source: ../
        target: /var/www/html
    user: "${USER_ID}:${USER_GID}"
    networks:
      app-net:
        ipv4_address: 172.16.238.20

networks:
  app-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24